on:
  push:
  pull_request:

name: Build PDF documents

jobs:
  build_pdf:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Setup pandoc
        uses: nikeee/setup-pandoc@v1

      #- name: Setup TeX Live
      #  uses: teatimeguest/setup-texlive-action@v2

      - name: Install pdflatex, from https://gist.github.com/rain1024/98dd5e2c6c8c28f9ea9d
        run: |
          sudo apt-get install texlive-latex-base
          sudo apt-get install texlive-fonts-recommended
          sudo apt-get install texlive-fonts-extra
          sudo apt-get install texlive-latex-extra

      - name: Remove old PDFs
        run: |
          cd boecker
          rm *.pdf
          cd ..

      - name: Create front pages
        run: |
          cd scripts
          ./goera_framsidor.sh
          cd ..

      - name: Upload PDF to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: processing_foer_ungdomar_pdfs.pdf
          path: boecker/*.pdf

